language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install tox
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
notifications:
  email:
    - pypeman@mhcomm.fr
