[tox]
envlist=py38
        py39
        py310

[testenv:py38]
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt
    flake8
commands=
    python -m flake8 pypeman
    pytest --cov=pypeman --cov-config=.coveragerc
    codecov
passenv=PYPEMAN_*,CODECOV_TOKEN,TRAVIS,TRAVIS_*

[testenv:py39]
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt
    flake8
commands=
    python -m flake8 pypeman
    pytest --cov=pypeman --cov-config=.coveragerc
    codecov
passenv=PYPEMAN_*,CODECOV_TOKEN,TRAVIS,TRAVIS_*

[testenv:py310]
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt
    flake8
commands=
    python -m flake8 pypeman
    pytest --cov=pypeman --cov-config=.coveragerc
    codecov
passenv=PYPEMAN_*,CODECOV_TOKEN,TRAVIS,TRAVIS_*
