[tox]
envlist = py310, py311, py312, py313, py314
skip_missing_interpreters = true

[testenv]
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt
    flake8
commands=
    python -m flake8 pypeman
    pytest --cov=pypeman --cov-config=.coveragerc
passenv=PYPEMAN_*
